version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  my_php_network:
    driver: bridge

services:
  app:
    build:
      context: docker
    restart: always
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - my_php_network
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notes_db
    ports:
      - "33061:3306"
    volumes:
      - "db_volume:/var/lib/mysql"
    networks:
      - my_php_network
